[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
ignore = "0.4.20"
lazy_static = "1.4.0"
regex = "1.7.3"
walkdir = "2.3.3"
